### ISSUE TITLE
❤ the screenshots in your Readme!

### ISSUE THREAD

**Issue by PySimpleGUI** [ReaseRZ/IPray#1]
Thank you for posting screenshots of your application in your readme!  ![image](https://github.com/ReaseRZ/IPray/assets/46163555/8b6e3a33-8e1c-483a-8f3e-bba9268924d6)

I know other visitors like seeing pictures and will be thankful to see them.

**Comment by ReaseRZ** [comment]
Be Pleasure to me if my program can be usefull for others 😄
